# Use the official Python base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file
COPY ./app/requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r ./app/requirements.txt .

# Copy the application code
COPY . .

# Expose the port specified in the FastAPI application
EXPOSE 80

# Define the command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]